### PR TITLE
chore: update generic scrapers readme and input schema

### PR DESCRIPTION
**Pull request by AndreyBykov**
- Remove Pseudo-Urls from readme/input
- add v3 breaking changes (enforced proxy usage, deprecation of pseudo-urls)

### CODE REVIEW

**Review by B4nan — COMMENTED** [review]
let me ask for final confirmation both @mnmkng and @jancurn, I remember there was some push back when we initially wanted to remove it (from the library), so just wanted to double check its fine to remove it from the input schema. 

also, to me this feels kind of weird, to remove it from the schema and call it deprecated - deprecated things can be still used, but here we are basically removing the UI, hence it cannot be used (by regular users)

**Comment by AndreyBykov** [comment]
Yeah, I also thought about those things. We could either remove that it's deprecated and keep as legit option, but I guess we really want to get rid of it. If that's the case - removing it from inputs keeps it working for existing scrapers, but new user would not have a choice other than using globs. But yeah - I just created this PR as it was mentioned in Slack to remove it.

**Comment by jancurn** [comment]
Guys, feel free to deprecate PseudoURLs but don't remove it yet, because you will piss off a ton of our core users. Keep in mind that these are our most grossing public actors; they really are our core product, and removing features people depend, without any advance warning or analysis of how many people depend on them, will break the trust of our users and drive them away.

**Comment by B4nan** [comment]
Yeah, that's what I thought, I'd keep it as is (if we want to remove the support at some point, e.g. in v4), or remove the "(deprecated)" part if we plan on keeping it for longer (no harm in keeping it deprecated for more than one major version).

**Comment by AndreyBykov** [comment]
Will do another small PR with removed `(deprecated)` and added `changes` 👍

**Pull request closed without merging**
