### PR TITLE
chore: login to testing account for e2e tests

### PR DESCRIPTION
**Pull request by vladfrangu**
Will run it first to ensure it works and merge if it passes

EDIT: Marked as draft as we need to discuss what to do about the tests we would run and also need to do some more configuration for them

### CODE REVIEW

**Comment by B4nan** [comment]
> EDIT: Marked as draft as we need to discuss what to do about the tests we would run and also need to do some more configuration for them

Discuss what? :]

**Comment by vladfrangu** [comment]
> > EDIT: Marked as draft as we need to discuss what to do about the tests we would run and also need to do some more configuration for them
> 
> Discuss what? :]

Well currently the e2e tests in this repository are just copies of the old ones from crawlee, which feels redundant...

**Comment by B4nan** [comment]
The ones in here are scraper tests, they test the scrapers, not the crawlee classes. We test them via inputs.

**Comment by vladfrangu** [comment]
Ohh, rightt. I will say I'm concerned at the fact the e2e test has been running for 3 hours without anything yielded tho...

**Comment by B4nan** [comment]
Yeah its broken, it needs to finish within an hour id say. It wasnt finishing locally either.

**Comment by vladfrangu** [comment]
Should I adapt the e2e tests to the same system we use on crawlee so we test on platform?

**Comment by B4nan** [comment]
Well, how? We need to test scrapers, not push new actors like we do in crawlee. I guess we could use the client somehow, but we dont want the same setup as with crawlee.

**Comment by B4nan** [comment]
I will merge this as it at least helps with one issue, but the E2E tests are not working correctly at all (the run script).

**Pull request merged**
